docs: update readme
frmscoe/frms-coe-startup-lib pull request #81
Opened 2024-08-12 13:00 UTC by rtkay123

# SPDX-License-Identifier: Apache-2.0

## What did we change?

## Why are we doing this?

## How was it tested?
- [ ] Locally
- [ ] Development Environment
- [ ] Not needed, changes very basic
- [x] Husky successfully run
- [x] Unit tests passing and Documentation done

2024-08-14 12:30 UTC, Sandy-at-Tazama requested changes
1. References to `frms-coe-lib` instead of `'frms-cp-startup-lib` 
![image](https://github.com/user-attachments/assets/711e86a8-31b4-4c78-9dde-13c7aaeba6f8)

and here
![image](https://github.com/user-attachments/assets/d6d5b200-3eb0-4981-97cb-56d19e5d9a66)

2. Reference to `jetstream`
![image](https://github.com/user-attachments/assets/c4108437-49d3-443e-a7d6-a58618614079)

and here
![image](https://github.com/user-attachments/assets/865f1ce0-c659-4d3b-84fb-b4c25d992405)

2024-08-14 12:45 UTC, rtkay123 commented
@Sandy-at-Tazama good catch! I updated it. Second reference to `frms-coe-lib` is intentional. That is where the link points to (the protofile which we use as the blueprint for encoding and decoding).

2024-08-16 07:34 UTC, Sandy-at-Tazama approved these changes

2024-08-19 07:30 UTC, JeanPierreNell approved these changes

2024-08-19 07:31 UTC, merged